### ISSUE TITLE
Mesh R-CNN and ShapeNet 

### ISSUE THREAD

**Issue by edward1christian** [facebookresearch/meshrcnn#113]
Hello,

I having a problem running the preprocess script on the ShapeNet V1 dataset. I have registered and downloaded the ShapeNetCoreV1 dataset files.
              `python tools/preprocess_shapenet.py \
--shapenet_dir ./datasets/shapenet/ShapeNetCore.v1 \
--shapenet_binvox_dir ./datasets/shapenet/ShapeNetCore.v1 \
--output_dir ./datasets/shapenet/ShapeNetV1processed \
--zip_output`

Unzipping ShapeNetCore.v1.zip and ShapeNetCore.v1.binvox.zip all extracted to same folder datasets/shapenet/ShapeNetCore.v1 .

I get the following error: 
`
Traceback (most recent call last):
  File "tools/preprocess_shapenet.py", line 317, in <module>
    main(args)
  File "tools/preprocess_shapenet.py", line 144, in main
    raise ValueError("Pre processing identified missing data points")
ValueError: Pre processing identified missing data points
`

I think this is a error with the dataset itself. Sorry if this is too basic question but am new to this all. Thanks in advance for the assistance.

I am Running on Ubuntu 22.04.2

**Comment by edward1christian** [comment]
The response given here is #47 is not very helpful to a newbie. Its like telling a lost traveler to look at the alignment of the stars to find a way home :-)
