### ISSUE TITLE
Running Demo without NVIDIA GPU

### ISSUE THREAD

**Issue by AnuragSahu** [facebookresearch/meshrcnn#15]
Hey,

I want to try out the demo but I dont have NVIDIA GPU on my system, when I try to run demo, by this command
```
python demo/demo.py --config-file configs/pix3d/voxelrcnn_R50_FPN.yaml --input MyImages/input/img1.png --output MyImages/output1 --onlyhighest MODEL.WEIGHTS meshrcnn://voxmesh_R50.pth

```
I am getting this error:

```
[02/27 09:42:23 demo]: Arguments: Namespace(config_file='configs/pix3d/voxelrcnn_R50_FPN.yaml', focal_length=20.0, input='MyImages/input/img1.png', onlyhighest=True, opts=['MODEL.WEIGHTS', 'meshrcnn://voxmesh_R50.pth'], output='MyImages/output1')
Traceback (most recent call last):
  File "demo/demo.py", line 222, in <module>
    cfg, vis_highest_scoring=args.onlyhighest, output_dir=os.path.join(args.output, im_name)
  File "demo/demo.py", line 44, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py", line 162, in __init__
    self.model = build_model(self.cfg)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/build.py", line 19, in build_model
    return META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py", line 41, in __init__
    pixel_mean = torch.Tensor(cfg.MODEL.PIXEL_MEAN).to(self.device).view(num_channels, 1, 1)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 192, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 102, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

Is it necessary to to have NVIDIA GPU for demo.py? or is it necessary to have it for running the GPU? if not is there a way to run demo without GPU?

**Comment by gkioxari** [comment]
Unfortunately, I have never tried to run this code on a cpu. If you wish to work on this and submit a PR that allows cpu-only runs, I am happy to review this. Note that we have added CPU support for all PyTorch3D operators, so you wouldn't have to worry about that!

**Comment by gkioxari** [comment]
I will close this issue and I will wait for a PR for cpu only support by anyone of you that needs this!

**Comment by pavan4** [comment]
Just wanted to add a note here that although meshrcnn doesn't seem to require a GPU, [detectron](https://github.com/facebookresearch/Detectron)  which is a dependency for this project cannot run on a CPU and requires a GPU [here](https://github.com/facebookresearch/Detectron/issues/126)

**Comment by pavan4** [comment]
fwiw, CPU only run was quite straightforward. I had to add the below line of code. Not sure if it worth creating a PR for this. 

`DEVICE: "cpu"` to the config under model: https://github.com/facebookresearch/meshrcnn/blob/ab0762f87bfd4cbdf4560982c5c33832a445380b/configs/pix3d/meshrcnn_R50_FPN.yaml#L2
