### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by umyta** [facebookresearch/meshrcnn#26]
Hi, I have just updated my pytorch3d, detectron2 and meshrcnn to the newest version this morning with the following configuration:

Ubuntu 16.04
python 3.8.2
pytorch 1.5.0
CUDA 10.2
detectron2 0.1.1
pytorch3d 0.1.1

However, when I run the code for pix3d training `python tools/train_net.py --num-gpus 8 --config-file configs/pix3d/meshrcnn_R50_FPN.yaml`, I got the following error:
```
ERROR 04/24 11:46:51 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File ".../detectron2/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File ".../detectron2/detectron2/engine/train_loop.py", line 215, in run_step
    loss_dict = self.model(data)
  File ".../anaconda3/envs/python38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File ".../anaconda3/envs/python38/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 445, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File ".../anaconda3/envs/python38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File ".../detectron2/detectron2/modeling/meta_arch/rcnn.py", line 130, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File ".../anaconda3/envs/python38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File ".../meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 152, in forward
    losses.update(self._forward_z(features, proposals))
  File ".../meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 198, in _forward_z
    proposals, _ = select_foreground_proposals(instances, self.num_classes)
  File ".../detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 71, in select_foreground_proposals
    fg_proposals.append(proposals_per_image[fg_idxs])
  File ".../detectron2/detectron2/structures/instances.py", line 134, in __getitem__
    ret.set(k, v[item])
  File ".../meshrcnn/meshrcnn/structures/voxel.py", line 75, in __getitem__
    return VoxelInstances(selected_data)
  File ".../meshrcnn/meshrcnn/structures/voxel.py", line 52, in __init__
    assert torch.is_tensor(voxels[0])
IndexError: list index out of range
```

Could someone give me some advice on what might have caused this? Thanks!

**Comment by gkioxari** [comment]
I will try to reproduce your error but I can't promise I will get to it in the following days.

In the meantime, could you put a `import pdb; pdb.set_trace()` before the assert statement and check what the content of `voxels` is? From what I gather `voxels` is likely empty. This could be because your optimization is behaving bizarrely. If you're training in <8 GPUs, set your base_lr to a lower value (choose a linear schedule).

**Comment by umyta** [comment]
I think last time I checked it was empty, but I'm not sure why it would be empty. The wired thing is that my earlier version worked fine, after updating all 3 repos, it stopped working.

**Comment by gkioxari** [comment]
Hi @umyta. I just re-trained the model with detectron2 and pytorch3d from master, and everything worked fine. I couldn't reproduce your error.

**Comment by gkioxari** [comment]
Maybe also try to install pytorch again!

**Comment by umyta** [comment]
My bad, I changed the batch size to 16 due to memory limit at the moment, and it gives the error, but size of 32 or above does not produce that error.

**Comment by ruizhaoz** [comment]
This probably be a long time ago. But I met the same problem. Do you guys know why changing the bach size would cause this bug?
