### ISSUE TITLE
undefined symbol: _ZN3c107Warning4warnENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by jiapei100** [facebookresearch/meshrcnn#39]
```console
 3   master  ✔  python demo/demo.py \ 
                    --config-file configs/pix3d/meshrcnn_R50_FPN.yaml \
                    --input /path/to/image \
                    --output output_demo \
                    --onlyhighest MODEL.WEIGHTS meshrcnn://meshrcnn_R50.pth
Traceback (most recent call last):
  File "demo/demo.py", line 11, in <module>
    from detectron2.data import MetadataCatalog
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/data/build.py", line 14, in <module>
    from detectron2.structures import BoxMode
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/structures/__init__.py", line 6, in <module>
    from .keypoints import Keypoints, heatmaps_to_keypoints
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/structures/keypoints.py", line 6, in <module>
    from detectron2.layers import interpolate
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: ~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c107Warning4warnENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by gkioxari** [comment]
You have likely not installed the needed libraries properly.

**Comment by jiapei100** [comment]
@gkioxari 

Hi, my bad... went to bed in a hurry... The above ERROR had been solved. You are correct. **detectron2** needs to be rebuilt.

However, **pytorch3d** is **NOT** built with **GPU** successfully, since I **JUST** use a simple `pip install pytorch3d`. Rebuilding **pytorch3d** from source now. By the way, current **ERROR** is:

```console
 56   master  ✔  pwd                                                                                               8s  ...... 
......
 57   master  ✔  python demo/demo.py \                                                                                  ...... 
                     --config-file configs/pix3d/meshrcnn_R50_FPN.yaml \
                     --input ../Mesh-R-CNN.jpg \
                     --output ../output_demo \
                     --onlyhighest MODEL.WEIGHTS ../models/meshrcnn_R50.pth
[06/16 05:47:04 demo]: Arguments: Namespace(config_file='configs/pix3d/meshrcnn_R50_FPN.yaml', focal_length=20.0, input='../Mesh-R-CNN.jpg', onlyhighest=True, opts=['MODEL.WEIGHTS', '../models/meshrcnn_R50.pth'], output='../output_demo')
/pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple)
/pytorch/aten/src/ATen/native/BinaryOps.cpp:81: UserWarning: Integer division of tensors using div or / is deprecated, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
Traceback (most recent call last):
  File "demo/demo.py", line 227, in <module>
    predictions = demo.run_on_image(img, focal_length=args.focal_length)
  File "demo/demo.py", line 59, in run_on_image
    predictions = self.predictor(image)
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/engine/defaults.py", line 216, in __call__
    predictions = self.model([inputs])[0]
  File "~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/modeling/meta_arch/rcnn.py", line 106, in forward
    return self.inference(batched_inputs)
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/modeling/meta_arch/rcnn.py", line 163, in inference
    results, _ = self.roi_heads(images, features, proposals, None)
  File "~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "....../meshrcnn/modeling/roi_heads/roi_heads.py", line 164, in forward
    pred_instances = self.forward_with_given_boxes(features, pred_instances)
  File "....../meshrcnn/modeling/roi_heads/roi_heads.py", line 185, in forward_with_given_boxes
    instances = self._forward_shape(features, instances)
  File "....../meshrcnn/modeling/roi_heads/roi_heads.py", line 357, in _forward_shape
    pred_meshes = self.mesh_head(mesh_features, init_mesh)
  File "~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "....../meshrcnn/modeling/roi_heads/mesh_head.py", line 228, in forward
    mesh, vert_feats = stage(x, mesh, vert_feats=vert_feats)
  File "~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "....../meshrcnn/modeling/roi_heads/mesh_head.py", line 183, in forward
    vert_feats_nopos = F.relu(graph_conv(vert_feats, mesh.edges_packed()))
  File "~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "~/.local/lib/python3.6/site-packages/pytorch3d/ops/graph_conv.py", line 71, in forward
    neighbor_sums = gather_scatter(verts_w1, edges, self.directed)
  File "~/.local/lib/python3.6/site-packages/pytorch3d/ops/graph_conv.py", line 154, in forward
    output = _C.gather_scatter(input, edges, directed, backward)
RuntimeError: Not compiled with GPU support.
```

**Comment by gkioxari** [comment]
pip install is only for CPU support. This is not just for PyTorch3D but for all libraries. If you want GPU support, install the conda package or from source. Please read the instructions carefully.

**Comment by jiapei100** [comment]
@gkioxari 
Thank you Georgia . I stopped using conda 2 years ago... 
Rebuilding Pytorch now, still ongoing, 70% ....

**Comment by gkioxari** [comment]
Please close the issue if your problems have been resolved! I also encourage you to start using conda again! It's how you install a lot of GPU packages like PyTorch.
