### ISSUE TITLE
Failed to install meshrcnn ...

### ISSUE THREAD

**Issue by jiapei100** [facebookresearch/meshrcnn#40]
It's saying **Successfully installed meshrcnn**. However, by checking the following message:

```console
 36   master  ✔  pip install --no-deps -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file://....../meshrcnn
Installing collected packages: meshrcnn
  Attempting uninstall: meshrcnn
    Found existing installation: meshrcnn 1.0
    Uninstalling meshrcnn-1.0:
      Successfully uninstalled meshrcnn-1.0
  Running setup.py develop for meshrcnn
Successfully installed meshrcnn
Traceback (most recent call last):
  File "~/.local/bin/pip", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 75, in main
    return command.main(cmd_args)
  File "~/.local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 114, in main
    return self._main(args)
  File "~/.local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 226, in _main
    self.handle_pip_version_check(options)
  File "~/.local/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 155, in handle_pip_version_check
    timeout=min(5, options.timeout)
  File "~/.local/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 100, in _build_session
    index_urls=self._get_index_urls(options),
  File "~/.local/lib/python3.6/site-packages/pip/_internal/network/session.py", line 249, in __init__
    self.headers["User-Agent"] = user_agent()
  File "~/.local/lib/python3.6/site-packages/pip/_internal/network/session.py", line 159, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "~/.local/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 634, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1983, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1414, in has_metadata
    return self._has(path)
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1854, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1731, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1688, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '~/.local/lib/python3.6/site-packages/meshrcnn-1.0-py3.6.egg'
```

and I doublchecked it's true that there is **NO** such file **~/.local/lib/python3.6/site-packages/meshrcnn-1.0-py3.6.egg**. Aftewards, I found there is an **egg** find produce under current subfolder **dist**. I just did a **copy** successfully.

```console
 57   master  ✘  ll ~/.local/lib/python3.6/site-packages/meshrcnn-1.0-py3.6.egg
ls: cannot access '~/.local/lib/python3.6/site-packages/meshrcnn-1.0-py3.6.egg': No such file or directory
 64   master  ✔  ls dist/
meshrcnn-1.0-py3.6.egg*
 65   master  ✔  cp dist/meshrcnn-1.0-py3.6.egg ~/.local/lib/python3.6/site-packages/   
```

Anyway, after that, I ended up with a failure demo as:
```console
 66   master  ✔  python demo/demo.py \
                     --config-file configs/pix3d/meshrcnn_R50_FPN.yaml \
                     --input ../Mesh-R-CNN.jpg \
                     --output ../output_demo \
                     --onlyhighest MODEL.WEIGHTS ../models/meshrcnn_R50.pth
Traceback (most recent call last):
  File "demo/demo.py", line 11, in <module>
    from detectron2.data import MetadataCatalog
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/data/build.py", line 14, in <module>
    from detectron2.structures import BoxMode
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/structures/__init__.py", line 6, in <module>
    from .keypoints import Keypoints, heatmaps_to_keypoints
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/structures/keypoints.py", line 6, in <module>
    from detectron2.layers import interpolate
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: ~/.local/lib/python3.6/site-packages/detectron2-0.1.3-py3.6-linux-x86_64.egg/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIfEEEPKNS_6detail12TypeMetaDataEv
```

**Comment by bottler** [comment]
You are using pytorch3d and detectron which are built using pytorch. I think you have a mismatched version of pytorch somewhere. The pytorch version (which I think for you is not a release version but a particular checkout on master) you have installed must also be the version used to build detectron and pytorch3d. Perhaps your detectron was built with a pytorch older than this PR https://github.com/pytorch/pytorch/pull/37632 being merged but your pytorch is newer.

**Comment by jiapei100** [comment]
@bottler 

You are right. I am using **torch 1.6.0a0+144e8dc**, instead of **torch=1.5.0**... Now, I even failed to build **meshrcnn**, with:

```console
 30   master  ✔  pip install --no-deps --prefix=~/.local/ .
Processing ....../meshrcnn
ERROR: Exception:
Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 430, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.ContextualVersionConflict: (torch 1.6.0a0+144e8dc (~/.local/lib/python3.6/site-packages), Requirement.parse('torch==1.5.0'), {'torchvision'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "~/.local/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "~/.local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 333, in run
    reqs, check_supported_wheels=not options.target_dir
  File "~/.local/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "~/.local/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "~/.local/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 325, in _get_abstract_dist_for
    req.check_if_exists(self.use_user_site)
  File "~/.local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 435, in check_if_exists
    self.req.name
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "~/.local/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.ContextualVersionConflict: (torch 1.6.0a0+144e8dc (~/.local/lib/python3.6/site-packages), Requirement.parse('torch==1.5.0'), {'torchvision'})
```

**Comment by bottler** [comment]
torchvision depends on torch as well, and has to be built consistently as well. It looks like you are using the latest release of torchvision, which uses the latest release of pytorch (1.5). You need the master of torchvision.

**Comment by jiapei100** [comment]
Still a couple of issues:

1. Why **must** I run `pip install -e .` instead of `python setup.py install --user` ? 

2. Failed to run `meshrcnn.__version__` and `meshrcnn.__file__`

```console
⚙ ✔  python                                                                                                                                                                                          ~ 
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import meshrcnn
>>> meshrcnn.__file__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'meshrcnn' has no attribute '__file__'
>>> meshrcnn.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'meshrcnn' has no attribute '__version__'
>>> 
```

3. Test on **pix3d** still failed.

```console
⚙ ✔  python demo/demo.py \
                       --config-file configs/pix3d/meshrcnn_R50_FPN.yaml \
                       --input datasets/pix3d/img \
                       --output output_demo \
                       --onlyhighest MODEL.WEIGHTS meshrcnn://meshrcnn_R50.pth
[06/24 14:35:57 demo]: Arguments: Namespace(config_file='configs/pix3d/meshrcnn_R50_FPN.yaml', focal_length=20.0, input='datasets/pix3d/img', onlyhighest=True, opts=['MODEL.WEIGHTS', 'meshrcnn://meshrcnn_R50.pth'], output='output_demo')
meshrcnn_R50.pth: 487MB [01:14, 6.51MB/s]                                                                                                                                                                      
Traceback (most recent call last):
  File "demo/demo.py", line 226, in <module>
    img = read_image(args.input, format="BGR")
  File "~/.local/lib/python3.6/site-packages/detectron2/data/detection_utils.py", line 113, in read_image
    with PathManager.open(file_name, "rb") as f:
  File "~/.local/lib/python3.6/site-packages/fvcore/common/file_io.py", line 575, in open
    path, mode, buffering=buffering, **kwargs
  File "~/.local/lib/python3.6/site-packages/fvcore/common/file_io.py", line 380, in _open
    opener=opener,
IsADirectoryError: [Errno 21] Is a directory: 'datasets/pix3d/img'
```

**Comment by bottler** [comment]
`pip install -e` and `python setup.py install` are very similar. The thing was you needed the `--no-deps` flag which is in pip (and which is quite dangerous).

Is 2 important? I don't think meshrcnn has them.

**Comment by gkioxari** [comment]
No response in 17 days. Closing this. Reopen if any issues arise.

**Comment by albertotono** [comment]
While trying the **demo.py** in Colab I have some issues with `import meshrcnn.data`

```
import meshrcnn.data  # noqa
import meshrcnn.modeling  # noqa
import meshrcnn.utils  # noqa
from meshrcnn.config import get_meshrcnn_cfg_defaults
from meshrcnn.evaluation import transform_meshes_to_camera_coord_system
```

I am receiving this error 

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-37-338fa45bd4bd> in <module>()
      1 # required so that .register() calls are executed in module scope
----> 2 import meshrcnn.data  # noqa
      3 import meshrcnn.modeling  # noqa
      4 import meshrcnn.utils  # noqa
      5 from meshrcnn.config import get_meshrcnn_cfg_defaults

ModuleNotFoundError: No module named 'meshrcnn.data'
```

`#noqa `shouldn't indicate that the linter should not check this line?! 

It is possible to test it here https://colab.research.google.com/drive/1LidibyH1yqEqOZSvDnI0Ry-vMrqxlLSr?usp=sharing
