### ISSUE TITLE
Extend to multi object meshrcnn

### ISSUE THREAD

**Issue by trevor-taeyeop** [facebookresearch/meshrcnn#66]
**I want to extend meshrcnn multi-object prediction version.**
I got error from this two-part (mesh, voxel), because of the stacking process.
Each objects has the different number of voxel points(verts) and mesh points(verts). 

**Q1. Could you advice how to extend multi-object version meshrcnn??** 
It would be appreciated if you let me know some simple examples.
I tried to adjust the number of points (Change Code), but not sure this is the correct method. 

**[Error Part]**

https://github.com/facebookresearch/meshrcnn/blob/89b59e6df2eb09b8798eae16e204f75bb8dc92a7/meshrcnn/structures/voxel.py#L23

https://github.com/facebookresearch/meshrcnn/blob/89b59e6df2eb09b8798eae16e204f75bb8dc92a7/meshrcnn/structures/mesh.py#L23

```
for obj in annos:
   ...:     print(obj['voxel'].shape)
   ...:     
torch.Size([105438, 3])
torch.Size([210464, 3])
torch.Size([175355, 3])
torch.Size([111317, 3])
torch.Size([95030, 3])
torch.Size([51192, 3])
torch.Size([88422, 3])
```

**[Origin Code]** 
https://github.com/facebookresearch/meshrcnn/blob/ab0762f87bfd4cbdf4560982c5c33832a445380b/meshrcnn/data/meshrcnn_transforms.py#L55-L61

**[Change Code]**  
```
    if len(annos) and "voxel" in annos[0]:
        if "voxel_num" in annos[0]:
            # todo check this min or max part
            # get min array
            if mode == "min":
                num = np.array([obj["voxel_num"] for obj in annos]).min()
                voxels = [obj["voxel"][:num] for obj in annos]
            elif mode == 'max':
                # get max array
                num = np.array([obj["voxel_num"] for obj in annos]).max()
                voxels = []
                for obj in annos:
                    tmp = torch.zeros(num, 3).float()
                    tmp[:obj["voxel_num"]] = obj["voxel"]
                    voxels.append(tmp)
        else:
            voxels = [obj["voxel"] for obj in annos]
        target.gt_voxels = VoxelInstances(voxels)

    if len(annos) and "mesh" in annos[0]:
        if "mesh_num" in annos[0]:
            num = np.array([obj["voxel_num"] for obj in annos]).max()
            meshes = []
            for obj in annos:
                tmp = torch.zeros(num, 3).float()
                tmp[:obj["mesh_num"]] = obj["mesh"][0]
                meshes.append((tmp,obj["mesh"][1]))
        else:
            meshes = [obj["mesh"] for obj in annos]
        target.gt_meshes = MeshInstances(meshes)
```

**[Full Error Message]**
```
ERROR [10/09 21:28:29 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/sdata1/workspace/detectron2/detectron2/engine/train_loop.py", line 142, in train
    self.run_step()
  File "/sdata1/workspace/detectron2/detectron2/engine/train_loop.py", line 235, in run_step
    loss_dict = self.model(data)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/sdata1/workspace/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 166, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/sdata1/workspace/meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 173, in forward
    losses.update(self._forward_shape(features, proposals))
  File "/sdata1/workspace/meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 335, in _forward_shape
    voxel_logits, proposals, loss_weight=self.voxel_loss_weight
  File "/sdata1/workspace/meshrcnn/meshrcnn/modeling/roi_heads/voxel_head.py", line 55, in voxel_rcnn_loss
    gt_voxels, instances_per_image.proposal_boxes.tensor, gt_K, voxel_side_len
  File "/sdata1/workspace/meshrcnn/meshrcnn/structures/voxel.py", line 23, in batch_crop_voxels_within_box
    voxels_tensor = torch.stack(voxels.data, 0) # (ba, N, 3)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 243562 and 184436 in dimension 1 at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/generic/THCTensorMath.cu:71
[10/09 21:28:29 d2.engine.hooks]: Total training time: 0:12:17 (0:00:00 on hooks)
[10/09 21:28:29 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 1297M
Traceback (most recent call last):
  File "/sdata1/workspace/detectron2/detectron2/engine/train_loop.py", line 142, in train
    self.run_step()
  File "/sdata1/workspace/detectron2/detectron2/engine/train_loop.py", line 235, in run_step
    loss_dict = self.model(data)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/sdata1/workspace/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 166, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/user/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/sdata1/workspace/meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 173, in forward
    losses.update(self._forward_shape(features, proposals))
  File "/sdata1/workspace/meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 335, in _forward_shape
    voxel_logits, proposals, loss_weight=self.voxel_loss_weight
  File "/sdata1/workspace/meshrcnn/meshrcnn/modeling/roi_heads/voxel_head.py", line 55, in voxel_rcnn_loss
    gt_voxels, instances_per_image.proposal_boxes.tensor, gt_K, voxel_side_len
  File "/sdata1/workspace/meshrcnn/meshrcnn/structures/voxel.py", line 23, in batch_crop_voxels_within_box
    voxels_tensor = torch.stack(voxels.data, 0) # (ba, N, 3)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 243562 and 184436 in dimension 1 at /opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/generic/THCTensorMath.cu:71
terminate called without an active exception
terminate called recursively
terminate called recursively

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

```

**Comment by gkioxari** [comment]
Please read https://github.com/facebookresearch/meshrcnn/issues/58
