### ISSUE TITLE
Issue on running demo script

### ISSUE THREAD

**Issue by HarryGateaux** [facebookresearch/meshrcnn#9]
Hi , thanks for sharing this fantastic library. I was trying to run the demo script using an image taken from the pix3d dataset. 

However I get this error. Apologies if I'm doing something silly here, I tried to find the issue but have been struggling
`````

` $ python demo/demo.py --config-file configs/pix3d/meshrcnn_R50_FPN.yaml --input "0041.png" --output output_demo --onlyhighest MODEL.WEIGHTS meshrcnn://meshrcnn_R50.pth


[02/16 15:54:30 demo]: Arguments: Namespace(config_file='configs/pix3d/meshrcnn_R50_FPN.yaml', focal_length=20.0, input='0041.png', onlyhighest=True, opts=['MODEL.WEIGHTS', 'meshrcnn://meshrcnn_R50.pth'], output='output_demo')

Traceback (most recent call last):
  File "demo/demo.py", line 227, in <module>
    predictions = demo.run_on_image(img, focal_length=args.focal_length)
  File "demo/demo.py", line 59, in run_on_image
    predictions = self.predictor(image)
  File "/home/anthony/miniconda3/envs/meshRCNN/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 196, in __call__
    predictions = self.model([inputs])[0]
  File "/home/anthony/miniconda3/envs/meshRCNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anthony/miniconda3/envs/meshRCNN/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 107, in forward
    return self.inference(batched_inputs)
  File "/home/anthony/miniconda3/envs/meshRCNN/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 169, in inference
    results, _ = self.roi_heads(images, features, proposals, None)
  File "/home/anthony/miniconda3/envs/meshRCNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anthony/repos/meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 181, in forward
    pred_instances = self.forward_with_given_boxes(features, pred_instances)
  File "/home/anthony/repos/meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 202, in forward_with_given_boxes
    instances = self._forward_mask(features, instances)
  File "/home/anthony/repos/meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 267, in _forward_mask
    return self.mask_head(mask_features, instances)
  File "/home/anthony/miniconda3/envs/meshRCNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given

```


`

**Comment by gkioxari** [comment]
Hi @HarryGateaux! 
I can't reproduce your error. 
Are you using the recent version of detectron2? There was a recent change introduced on the mask head (see [commit](https://github.com/facebookresearch/detectron2/commit/bbf3b163058b19d00ae791b140c5b52a32746618)). Since this codebase depends on d2 master, can you make sure you have the recent version of d2?

**Comment by noamgat** [comment]
I confirm that the demo script works if installing detectron2 and pytorch3d via the "pip git" method.

**Comment by HarryGateaux** [comment]
Thanks for the tip with detectron2. I had installed using pre-built (as per https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md) which I guess is slightly out of date. When I install from source the demo works perfectly for meshRCNN

Thanks a lot!
