### ISSUE TITLE
Boxes objects are incorrect while training (data from microscopy; generic rot, trans, and K values)

### ISSUE THREAD

**Issue by caniko** [facebookresearch/meshrcnn#94]
I am in the process of using microscopy data for training the network. Moreover, I would like to use ideal values for rotation and translation matrix, and K as I don't have the means for retrieving the real parameters.

I set the rotation and translation to I³, and K to (1, 1, 1). Moreover, I am getting the following error after importing the models to the runtime:

```
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/admin/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/admin/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/admin/detectron2_repo/detectron2/data/common.py", line 43, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/admin/meshrcnn/meshrcnn/data/meshrcnn_transforms.py", line 181, in __call__
    dataset_dict["instances"] = instances[instances.gt_boxes.nonempty()]
  File "/home/admin/detectron2_repo/detectron2/structures/instances.py", line 139, in __getitem__
    ret.set(k, v[item])
  File "/home/admin/meshrcnn/meshrcnn/structures/mesh.py", line 77, in __getitem__
    return MeshInstances(selected_data)
  File "/home/admin/meshrcnn/meshrcnn/structures/mesh.py", line 54, in __init__
    raise IndexError(meshes) from e
IndexError: []
```

Note that I added a few lines code for printing out some variables for debugging purposes. `raise IndexError(meshes) from e` is simply to understand that `mesh[0][0]` leads to an error not because of the contents being false, but that `mesh` is empty, which leads to the IndexError.

It seems that there is something wrong with x. Any ideas on what the cause might be?

**Extra information**
Relevant part of config yaml:
```
INPUT:
  MIN_SIZE_TRAIN: (0,)
  MAX_SIZE_TRAIN: 1024
```

**Comment by gkioxari** [comment]
It sounds like you changed the dataset and you are facing issues with the code. I think you need to start by debugging your data loader and verifying that your data is right. I don't think that there is anything I can do to help.

**Comment by caniko** [comment]
The issue is definitely with the data loader, but I am using the pix3d data loader. I have not changed anything in the loader. Here is one of the datasets that lead to an `IndexError` (bbox looks strange):
```
old: (109, 91, 3)
new: (109, 91, 3)
transforms: TransformList[NoOpTransform(), HFlipTransform(width=91)]
gens: [ResizeShortestEdge(short_edge_length=(0,), max_size=1024, sample_style='choice'), RandomFlip(prob=0.5)]
anno: [{'iscrowd': 0, 'bbox': array([-1836,   933,  -824,  1947]), 'category_id': 0, 'segmentation': tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]), 'mesh': (tensor([[ 45.4203,  44.1078, -21.0877],
        [ 45.4168,  45.1267, -21.0313],
        [ 45.4157,  46.1353, -21.0054],
        ...,
        [-43.1402, -29.2852,  28.5380],
        [-43.1373, -28.2847,  28.5980],
        [-43.1379, -27.2265,  28.6986]]), tensor([[   14,    51,     4],
        [   14,    52,    51],
        [    5,    53,    14],
        ...,
        [12152, 12325, 12154],
        [12154, 12325, 12326],
        [12154, 12326, 12327]])), 'K': [1, 45.5, 54.5], 'R': tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]), 't': tensor([1., 1., 1.]), 'bbox_mode': <BoxMode.XYXY_ABS: 0>, 'dz': tensor(10.1694)}]
```

**Comment by caniko** [comment]
Any ideas about this one?

```
Traceback (most recent call last):
  File "tools/train_net.py", line 108, in <module>
    args=(args,),
  File "/home/admin/detectron2_repo/detectron2/engine/launch.py", line 59, in launch
    daemon=False,
  File "/home/admin/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/admin/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/admin/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/admin/detectron2_repo/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/home/admin/meshrcnn/tools/train_net.py", line 96, in main
    return trainer.train()
  File "/home/admin/detectron2_repo/detectron2/engine/defaults.py", line 431, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/admin/detectron2_repo/detectron2/engine/train_loop.py", line 138, in train
    self.run_step()
  File "/home/admin/detectron2_repo/detectron2/engine/defaults.py", line 441, in run_step
    self._trainer.run_step()
  File "/home/admin/detectron2_repo/detectron2/engine/train_loop.py", line 232, in run_step
    loss_dict = self.model(data)
  File "/home/admin/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/.local/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/admin/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/detectron2_repo/detectron2/modeling/meta_arch/rcnn.py", line 166, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/home/admin/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 154, in forward
    losses.update(self._forward_mask(features, proposals))
  File "/home/admin/meshrcnn/meshrcnn/modeling/roi_heads/roi_heads.py", line 244, in _forward_mask
    loss_mask, target_masks = mask_rcnn_loss(mask_logits, proposals)
  File "/home/admin/meshrcnn/meshrcnn/modeling/roi_heads/mask_head.py", line 43, in mask_rcnn_loss
    instances_per_image.gt_masks, instances_per_image.proposal_boxes.tensor, mask_side_len
  File "/home/admin/meshrcnn/meshrcnn/structures/mask.py", line 78, in batch_crop_masks_within_box
    return torch.stack(results, dim=0).to(device=device)
RuntimeError: stack expects each tensor to be equal size, but got [37, 28, 28] at entry 0 and [27, 28, 28] at entry 1
```
Here is some info about the data that caused the error:
```
result_len: 4
masks: torch.Size([4, 61, 144, 3]); boxes: tensor([[  0.0000,   0.0000, 144.0000,  40.4231],
        [ 22.0410,   7.2234, 104.4718,  53.9213],
        [ 30.9198,   0.5787, 117.8307,  61.0000],
        [ 40.2607,   1.5484, 135.2612,  61.0000]])
1st_mask: torch.Size([61, 144, 3])
mask_side_len: 28
```

**Comment by matteopantano** [comment]
Hi @caniko I am getting the same error as the last one. How did you solve?
